apiVersion: v1
kind: Pod
metadata:
  name:	nginx-multiple-ports
  labels:
    app: nginx-multple-ports
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      name: https
      protocol: TCP
